import type { Metadata } from "next";
import {Chicle, Chivo, Cormorant_Upright, Geist, Geist_Mono} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const cormorant = Cormorant_Upright({
    variable: "--font-cormorant-upright",
    subsets: ["latin"],
    weight: ['300', "500"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const chicle = Chicle({
    weight: ["400"],
    variable: "--font-chicle" ,
    subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cormorant.variable} ${chicle.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
